name: 'Bash Loop for Env Vars'
description: 'Use env var for a second step to consume'
inputs:
  destinationFolder:  # id of input
    description: 'This folder path reads the input for the bash script to create a env with multiple vars'
    required: true
    default: '~'
outputs:
  copied_envs:
    description: "custom env output to use index ref for input use"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo File Path to Read ${{ inputs.destinationFolder }}.
      shell: bash
    - id: number-of-strings-read
      run: ${{ github.action_path }}/extract.sh
      shell: bash
    - run: echo "::set-output ::$(echo $envVar)"
      shell: bash          
